x-default_env_variables: &default_env_variables
  SERVER_PORT: 8080
  REDIS_HOST: "redis"
  PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
  PAYMENT_PROCESSOR_DEFAULT_TOKEN: "123"
  PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
  PAYMENT_PROCESSOR_FALLBACK_TOKEN: "123"
  MONGO_INITDB_ROOT_HOST: "mongodb"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "password"
  MONGO_INITDB_ROOT_DATABASE: "payment-database"
  JAVA_OPTS: "-Xmx256m -Xms256m"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: payment-database
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rinha

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - rinha

  api1:
    image: augustocsrf/rinha-2025-java:latest
    container_name: java-rinha-api-1
    ports:
      - "8081:8080"
    environment:
      <<: *default_env_variables
      REDIS_QUEUE: payment_queue_1
    restart: unless-stopped
    networks:
      - payment-processor
      - rinha

  api2:
    image: augustocsrf/rinha-2025-java:latest
    container_name: java-rinha-api-2
    ports:
      - "8082:8080"
    environment:
      <<: *default_env_variables
      REDIS_QUEUE: payment_queue_2
    restart: unless-stopped
    networks:
      - payment-processor
      - rinha

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - rinha

networks:
  rinha:
    driver: bridge
  payment-processor:
    external: true